"""
app/core/models/base.py

Shared declarative building blocks for all ORM models in ChatToSales.

Inheritance hierarchy:
    Base              ← SQLAlchemy DeclarativeBase + AsyncAttrs
    ├── BaseModel     ← Base + UUID PK + server-side timestamps
    └── TenantModel   ← BaseModel + tenant_id FK + index

Usage
-----
# Every-tenant record (most models):
class Customer(TenantModel):
    __tablename__ = "customers"
    ...

# System-level record (no tenant):
class SystemConfig(BaseModel):
    __tablename__ = "system_configs"
    ...
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Index, String, func
from sqlalchemy.orm import Mapped, mapped_column

from app.infra.database import Base


# ── BaseModel ─────────────────────────────────────────────────────────────────


class BaseModel(Base):
    """
    Abstract base for every ORM model.

    Provides:
    - id          UUID primary key, generated by the application layer so it is
                  available before the INSERT round-trip completes.
    - created_at  Set once by Postgres on INSERT via server_default.
    - updated_at  Refreshed by Postgres on every UPDATE via onupdate.
    """

    __abstract__ = True  # never mapped to a table directly

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        comment="UUID v4 primary key",
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        comment="Row creation timestamp (set by database)",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        comment="Last update timestamp (maintained by database)",
    )


# ── TenantMixin ───────────────────────────────────────────────────────────────


class TenantMixin:
    """
    Adds a tenant_id column to any BaseModel subclass.

    Rules:
    - tenant_id is mandatory (nullable=False) — every multi-tenant record must
      belong to a tenant.
    - An index is declared via __table_args__ on the concrete model so it can
      be combined with other indices (see TenantModel).
    - All queries MUST filter on tenant_id. The application service layer is
      responsible for injecting it; the DB layer does not enforce row-level
      security here (that can be added later via Postgres RLS).
    """

    tenant_id: Mapped[str] = mapped_column(
        String(36),
        nullable=False,
        index=True,
        comment="Owning tenant UUID — all reads/writes must be scoped to this value",
    )


# ── TenantModel ───────────────────────────────────────────────────────────────


class TenantModel(TenantMixin, BaseModel):
    """
    Convenience base combining BaseModel + TenantMixin.

    Use this for the vast majority of business models (Customer, Order, etc.)
    """

    __abstract__ = True
