"""
app/modules/onboarding/catalogue_templates.py

Starter items per business category — used in onboarding Paths C (Q&A) and D (skip).

30 items per category covers the most common products Nigerian informal market
traders carry. Path C walks the trader through these one at a time (with skip
option). Path D pre-loads them with blank prices that fill in as orders arrive.
"other" has no pre-loaded items — Q&A is skipped and Path D is recommended.
"""

from app.modules.onboarding.models import BusinessCategory

CATEGORY_DISPLAY_NAMES: dict[str, str] = {
    BusinessCategory.PROVISIONS: "Provisions and groceries",
    BusinessCategory.FABRIC: "Fabric and clothing",
    BusinessCategory.FOOD: "Food and cooked meals",
    BusinessCategory.ELECTRONICS: "Electronics and phones",
    BusinessCategory.COSMETICS: "Cosmetics and beauty",
    BusinessCategory.BUILDING: "Building materials",
    BusinessCategory.OTHER: "Something else",
}

# Short label used in the category confirmation message, e.g. "Provisions! Good choice."
CATEGORY_SHORT_NAMES: dict[str, str] = {
    BusinessCategory.PROVISIONS: "Provisions",
    BusinessCategory.FABRIC: "Fabric",
    BusinessCategory.FOOD: "Food",
    BusinessCategory.ELECTRONICS: "Electronics",
    BusinessCategory.COSMETICS: "Cosmetics",
    BusinessCategory.BUILDING: "Building materials",
    BusinessCategory.OTHER: "Got it",
}

# 30 starter items per category.
# "other" has no pre-loaded items — Q&A is skipped for that category.
CATEGORY_ITEMS: dict[str, list[str]] = {
    BusinessCategory.PROVISIONS: [
        "Indomie Carton",
        "Rice 50kg (Mama Gold)",
        "Rice 25kg",
        "Peak Milk 400g",
        "Peak Milk 900g",
        "Milo 400g",
        "Milo 200g",
        "Bournvita 500g",
        "Nescafe 200g",
        "Golden Morn 1kg",
        "Omo Washing Powder 500g",
        "Ariel Washing Powder 500g",
        "Garri 10kg",
        "Semolina 1kg",
        "Semo 1kg",
        "Geisha Sardine (tin)",
        "Titus Sardine (tin)",
        "Cowbell Milk (tin)",
        "Gino Tomato Puree (tin)",
        "Nagiko Tomato Puree (tin)",
        "Vegetable Oil 5L",
        "Groundnut Oil 5L",
        "Sugar 1kg (Dangote)",
        "Salt (Dangote)",
        "Knorr Seasoning Cubes (carton)",
        "Maggi Seasoning Cubes (carton)",
        "Spaghetti (pack)",
        "Macaroni (pack)",
        "Dettol 250ml",
        "Vaseline 200ml",
    ],
    BusinessCategory.FABRIC: [
        "Plain Ankara (per yard)",
        "Printed Ankara (per yard)",
        "Lace fabric (per yard)",
        "Swiss lace (per yard)",
        "Cord lace (per yard)",
        "Adire (per yard)",
        "Tie-dye fabric (per yard)",
        "Sequence fabric (per yard)",
        "Guinea brocade (per yard)",
        "English fabric (per yard)",
        "Wool fabric (per yard)",
        "Aso-oke (per set)",
        "George fabric (per set)",
        "Atiku fabric (per yard)",
        "Hollandaise (per yard)",
        "Cotton fabric (per yard)",
        "Crepe fabric (per yard)",
        "Chiffon fabric (per yard)",
        "Ankara ready-made top",
        "Ankara ready-made skirt",
        "Ready-made gown",
        "Native agbada (per set)",
        "Kaftan (per piece)",
        "Plain white fabric (per yard)",
        "Net fabric (per yard)",
        "Velvet fabric (per yard)",
        "Denim fabric (per yard)",
        "Taffeta fabric (per yard)",
        "Ankara face cap",
        "Fabric bag",
    ],
    BusinessCategory.FOOD: [
        "Jollof rice (per plate)",
        "Fried rice (per plate)",
        "White rice and stew (per plate)",
        "Eba (per plate)",
        "Amala (per plate)",
        "Pounded yam (per plate)",
        "Fufu (per plate)",
        "Egusi soup (per serving)",
        "Okra soup (per serving)",
        "Bitterleaf soup (per serving)",
        "Afang soup (per serving)",
        "Ogbono soup (per serving)",
        "Buka stew (per serving)",
        "Pepper soup (per serving)",
        "Ofe akwu (per serving)",
        "Efo riro (per serving)",
        "Beans (per plate)",
        "Akara (per piece)",
        "Moi moi (per wrap)",
        "Grilled fish (per piece)",
        "Fried fish (per piece)",
        "Ponmo (per wrap)",
        "Goat meat (per piece)",
        "Chicken (per piece)",
        "Turkey (per piece)",
        "Assorted meat (per wrap)",
        "Soft drink (per bottle)",
        "Water (per bottle)",
        "Zobo (per cup)",
        "Chapman (per cup)",
    ],
    BusinessCategory.ELECTRONICS: [
        "Phone charger (generic)",
        "iPhone charger",
        "Samsung charger (Type-C)",
        "Budget earphones",
        "Wireless earbuds",
        "Power bank 10,000mAh",
        "Power bank 20,000mAh",
        "USB cable (Type-C)",
        "USB cable (Lightning)",
        "Screen protector",
        "Phone case",
        "Bluetooth speaker",
        "Torch / flashlight",
        "Extension box (4-way)",
        "Memory card 32GB",
        "Memory card 64GB",
        "USB flash drive 16GB",
        "USB flash drive 32GB",
        "Bluetooth earpiece",
        "Car charger",
        "Phone holder (car mount)",
        "Selfie stick",
        "Portable USB fan",
        "Budget smart watch",
        "Calculator",
        "Electric shaver",
        "Hair trimmer",
        "Pocket radio",
        "Rechargeable lamp",
        "USB hub (4-port)",
    ],
    BusinessCategory.COSMETICS: [
        "Fair & White So White cream",
        "Carotone body cream",
        "Vaseline 400ml",
        "Nivea cream",
        "Raw shea butter",
        "Coconut oil",
        "Dark & Lovely relaxer kit",
        "Optimum relaxer kit",
        "Hair extensions (per pack)",
        "Hair attachment",
        "Brazilian hair (per bundle)",
        "Lipstick",
        "Lip gloss",
        "Foundation",
        "Face powder",
        "Eyebrow pencil",
        "Mascara",
        "Eyeliner",
        "Eye shadow palette",
        "Blush",
        "Highlighter",
        "Concealer",
        "Setting spray",
        "Body lotion (large)",
        "Nivea body spray",
        "Perfume (small)",
        "Deodorant",
        "Face wash",
        "Sunscreen",
        "Nail polish",
    ],
    BusinessCategory.BUILDING: [
        "Cement (per bag, Dangote)",
        "Cement (per bag, BUA)",
        "Iron rod 12mm (per length)",
        "Iron rod 16mm (per length)",
        "Roofing sheet (per piece)",
        "Dulux paint 5L",
        "Berger paint 5L",
        "Paint 20L",
        "Tiles 60x60 (per carton)",
        "Tiles 30x30 (per carton)",
        "Plywood (per sheet)",
        "MDF board (per sheet)",
        "Door handle (per set)",
        "PVC pipe 3/4 inch (per length)",
        "PVC pipe 1 inch (per length)",
        "Water tank 500L",
        "Galvanized pipe",
        "Electrical wire (per roll)",
        "Wall socket",
        "Light switch",
        "Window glass (per sheet)",
        "Padlock (medium)",
        "Padlock (large)",
        "Door hinge (per pair)",
        "Screws (per pack)",
        "Nails (per kg)",
        "Sand (per trip)",
        "Gravel (per trip)",
        "Block (per piece)",
        "Plank (per piece)",
    ],
    BusinessCategory.OTHER: [],
}


def get_items(category: str) -> list[str]:
    """Return the starter item list for a category, defaulting to empty."""
    return CATEGORY_ITEMS.get(category, [])


def get_display_name(category: str) -> str:
    """Return the human-readable category label."""
    return CATEGORY_DISPLAY_NAMES.get(category, category.title())
